version: '2'

volumes:
  node-red-data:
  grafana-data:
  zerotier-config:

services:
  # ------------------------------------------------------------------------------------
  # Node-RED
  # ------------------------------------------------------------------------------------
  node-red:
    image: nodered/node-red
    container_name: node-red
    privileged: true
    restart: unless-stopped
    volumes:
        - 'node-red-data:/data'
    ports:
        - 1880:1880
    cap_add:
        - SYS_RAWIO
    devices:
        - "/dev/mem:/dev/mem"
        - "/dev/gpiomem:/dev/gpiomem"
  # ------------------------------------------------------------------------------------
  # Grafana
  # ------------------------------------------------------------------------------------
  grafana:
    image: bh.cr/balenalabs/dashboard
    container_name: grafana
    restart: unless-stopped
    volumes:
      - "grafana-data:/data"
    environment:
      - "GF_SERVER_ROOT_URL=/grafana"
      - "GF_SERVER_SERVE_FROM_SUB_PATH=true"
  # ------------------------------------------------------------------------------------
  # Implementar conexion a ZeroTier-One
  # ------------------------------------------------------------------------------------
  zerotier:
      image: zerotier/zerotier:latest
      container_name: zerotier
      volumes:
          - "zerotier-config:/var/lib"
      cap_add:
        - net_admin
      devices:
        - /dev/net/tun
      restart: unless-stopped
      network_mode: host
