version: '2'

volumes:
  node-red-data:
  zerotier-config:

services:
  # ------------------------------------------------------------------------------------
  # Node-RED
  # ------------------------------------------------------------------------------------
  node-red:
    image: nodered/node-red:4.0.9-22-minimal
    container_name: node-red
    privileged: true
    restart: unless-stopped
    volumes:
        - 'node-red-data:/data'
    ports:
        - 1880:1880
  # ------------------------------------------------------------------------------------
  # Implementar conexion a ZeroTier-One
  # ------------------------------------------------------------------------------------
  zerotier:
      image: zerotier/zerotier:latest
      container_name: zerotier
      volumes:
          - "zerotier-config:/var/lib"
      cap_add:
        - net_admin
      devices:
        - /dev/net/tun
      restart: unless-stopped
      network_mode: host
